language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-2.4.1
  - rbx-2
  - ruby-head
  - jruby-19mode
  - jruby-head
script:
  - bundle exec rspec

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

notifications:
  email:
    - jwaterfaucett@gmail.com
